# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StoreDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorderqueuemodels',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 13, 11, 46, 21, 35708, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
