# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreDetails', '0002_foodorderqueuemodels_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifoServiceQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('food_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreDetails.FoodMenuModels')),
            ],
        ),
        migrations.RemoveField(
            model_name='foodorderqueuemodels',
            name='time_stamp',
        ),
    ]
