# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreDetails', '0005_remove_fifoservicequeue_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fifoservicequeue',
            name='store_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StoreDetails.StoreModels'),
        ),
    ]
