# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpdateSeats', '0003_auto_20170513_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableoccupancytimemodels',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
